# Load DSL and Setup Up Stages
require 'capistrano/setup'

# Includes default deployment tasks
require 'capistrano/deploy'

# Includes tasks from other gems included in your Gemfile
#
# For documentation on these, see for example:
#
#   https://github.com/capistrano/rvm
#   https://github.com/capistrano/rbenv
#   https://github.com/capistrano/chruby
#   https://github.com/capistrano/bundler
#   https://github.com/capistrano/rails/tree/master/assets
#   https://github.com/capistrano/rails/tree/master/migrations
#
# require 'capistrano/rvm'
# require 'capistrano/rbenv'
# require 'capistrano/chruby'
# require 'capistrano/bundler'
# require 'capistrano/rails/assets'
# require 'capistrano/rails/migrations'

# Loads custom tasks from `lib/capistrano/tasks' if you have any defined.
Dir.glob('lib/capistrano/tasks/*.cap').each { |r| import r }

before :deploy, :ensure_directories_exist do
	mkdir_p '/mtw/sys/sample/log'
	#run "sudo chown -R root:root /mtw/sys/sample/log"
end

before :deploy, :stop_sample do
	on roles(:app) do
		#execute "ruby /mtw/sys/sample/daemon.rb stop"
	end
end

after :deploy, :configure_ib do
	on roles(:app) do
		execute "cd /mtw/sys/sample && mtw configure"
	end
end

after :deploy, :start_sample do
	on roles(:app) do
		execute "ruby /mtw/sys/sample/daemon.rb start"
	end
end